services:
  - type: web
    name: admin-dashboard
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    healthCheckPath: /
    healthCheckTimeout: 300
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        sync: true
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: admin-dashboard-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: admin-dashboard-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: admin-dashboard-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: admin-dashboard-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: admin-dashboard-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_DRIVER
        value: log
      - key: FILESYSTEM_DISK
        value: local
    numInstances: 1
    autoDeploy: true
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=8080

  - type: redis
    name: admin-dashboard-redis
    plan: free
    ipAllowList: []

databases:
  - name: admin-dashboard-db
    databaseName: admin_dashboard
    user: admin
    plan: free 